### ISSUE TITLE
Format numbers with commas

### ISSUE THREAD

**Issue by clokep** [thundernest/stats#2]
This isn't a huge deal but I think adding commas (I know this is US-centric...) to the numbers on stats.thunderbird.net would make the table of daily estimates would make it much more readable. (Each time I look I have to ask "Is this 8 million, 80 million or 800 thousand?")

It might also help to right-align the ADI column, although the data isn't fixed-width, so maybe that doesn't matter much.

**Comment by Sancus** [comment]
I added commas to the table for now. The mouseovers use spaces, which is the ISO standard, and I may switch over the table to that later... going to make some additional changes and graphs to this page soon though.

https://github.com/thundernest/stats/commit/fee5ff421d94b18743d89d650237be0fdefce52c adds commas and it should be live a few hours after this comment.

**Comment by clokep** [comment]
Thanks! Spaces would work too, just some way to differentiate the sets of numbers. Looks great now!
